### ISSUE TITLE
Accessibility - focus gets trapped

### ISSUE THREAD

**Issue by jackmakesthings** [mjbp/storm-tab-accordion#1]
Nice library! I've noticed an issue while using it. While navigating the page via keyboard (tabbing through), you can focus the first tab title, and if there are any links inside the tab content, those can also be reached. However, you get stuck there. It's not possible to move focus from the tab container to whatever comes after it on the page. The same problem is present when it's in accordion view. 

Interestingly, if there are any links or other focusable elements inside the tab contents, it works much better. If my active tab has some links, I can tab through them, and after hitting the last one, focus moves to the next tab's title. Hitting tab again makes the next tab active (a little odd, but okay), or if I'm on the last tab, it moves focus to the next thing on the page. Perfect!

But if the tab _doesn't_ have anything focusable inside it, the focus gets stuck at the top of the tab and can't be moved forward.

(I experienced this in the latest Chrome browser, on a Mac, but I don't think the issue is platform-related.)

**Comment by mjbp** [comment]
Thanks for using the module and for raising this issue, it's much appreciated.

I've just pushed an update that _should_ resolve it - moving the target of the tab link to the inner element of the tab section (previously focus was getting stuck on the title). I've updated the example HTML and CSS to reflect this.
