### ISSUE TITLE
Option to close all accordion/tabs on mobile/dekstop

### ISSUE THREAD

**Issue by evandiamond** [mjbp/storm-tab-accordion#5]
@mjbp Would it be possible to have all "accordion/tabs" closed on mobile/desktop and/or the ability to close all accordion/tabs on mobile.

Right now it seems you have to have at least one open by default, but it might be a nice addition if you could collapse **all** via an option setting. Thoughts?

Something like this:
`collapsedMobile: true`

**Comment by mjbp** [comment]
@evandiamond Sorry for the tardy responses, project work taking all of our time at the moment.

It would be technically possible but there are a few reasons relating to accessibility why we wouldn't want to bake it in to this module.

At it's core this module uses the tab pattern as defined in the WAI best practices, attempting to use the tabs/tabpanel roles to make the component as accessible as possible. The accordion  buttons are really just another way of triggering the tabs, which are the real source of truth for this part of the DOM in the accessibility tree.

The WAI tab pattern prescribes that one should always be open, but if you want to circumvent that you can fork a version that replaces the toggle function with something like:

```
toggle(i) {
    this.close(this.current);
    if(this.current === i) { 
        !!window.history.pushState && history.pushState('', document.title, `${window.location.pathname}${window.location.search}`);
        return;
    }        
    !!window.history.pushState && window.history.pushState({ URL: this.tabs[i].getAttribute('href') }, '', this.tabs[i].getAttribute('href'));
    this.open(i);
    return this;
}
```

That would result in tabs that could have all panels hidden. To separate the behaviour of the tabs and the accordion buttons and the way that the state of the component is reported in the aria attributes based on whether it is an accordion or tabpanel is a more fundamental change to the whole module.

The module (and any assistive technology that consumes it) doesn't know if it looks like an accordion or tab to the user, or at which screen sizes the presentation change, all of that is dealt with by CSS. It is always a tabpanel as far as the accessibility tree is concerned. Coupling the functionality of the component to the screen size is something that would have to be done very carefully if you wanted to preserve accessibility - you can't change the role (in the ARIA sense) after the initial page render and have assistive technology know about it.

If you're concerned about accessibility I think you'd have to move away from the tab pattern as the underlying mechanism. The accordion pattern https://www.w3.org/TR/wai-aria-practices-1.1/#accordion or perhaps the disclosure pattern https://www.w3.org/TR/wai-aria-practices-1.1/#disclosure would be better starting points. Either way I think it would be a whole new module.

**Comment by evandiamond** [comment]
Wow! I really appreciate the well thought out response. I appreciate the time you put into that.
